#!/bin/bash
mkdir bin
cp -v {controller.py,maxvalue,scale,minvalue,path.py} bin
chmod +x bin/controller.py

echo "Installing..."
sudo ./etc/init.d/brightness-controller.sh
sudo cp etc/init.d/brightness-controller.sh /etc/init.d/
sudo chmod 744 /etc/init.d/brightness-controller.sh
sudo chown root:root /etc/init.d/brightness-controller.sh
sudo ln -s /etc/init.d/brightness-controller.sh /etc/rc2.d/S02brightness-controller.sh
DIR=$(pwd .)/bin
sudo ln -s $DIR/controller.py /bin/brightnessController

echo ""
echo "Installation Complete..."
echo "Use the command brightnessController to see usage"
echo "Please Restart your computer..."
